/**
 * Gemini fallback for VidhyaAI.
 *
 * VidhyaAI is Sarvam-first — every core study mode is generated by Sarvam AI.
 * But on the free "starter" tier sarvam-30b (a reasoning model, 4096-token
 * output cap) sometimes over-reasons past the cap on heavier requests and
 * returns nothing. To keep the app rock-solid, this Gemini client acts as a
 * safety net: if Sarvam fails/times out (or for the reasoning-heavy planner &
 * course modes it can't handle), we transparently fall back to gemini-2.5-flash,
 * asking for the exact same JSON shape so the UI is unaffected.
 *
 * Configure GEMINI_API_KEY to enable. If unset, the fallback is simply
 * unavailable and the app behaves as before (Sarvam-only).
 */

const apiKey = process.env.GEMINI_API_KEY;

/** True when a Gemini key is configured, so callers can decide to fall back. */
export const GEMINI_AVAILABLE = !!apiKey;

const URL =
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

const SYSTEM =
  "You are an expert study assistant. Respond with ONLY one valid JSON object " +
  "matching the requested shape — no markdown, no code fences, no commentary.";

/**
 * Send a prompt to Gemini and return the raw JSON text (parseJson handles it).
 * Uses responseMimeType application/json so Gemini emits clean, parseable JSON.
 */
export async function geminiChat(userContent: string): Promise<string> {
  if (!apiKey) throw new Error("Gemini not configured");

  const res = await fetch(URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
    body: JSON.stringify({
      system_instruction: { parts: [{ text: SYSTEM }] },
      contents: [{ parts: [{ text: userContent }] }],
      generationConfig: {
        responseMimeType: "application/json",
        temperature: 0.4,
        maxOutputTokens: 8192,
      },
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Gemini ${res.status}: ${detail.slice(0, 200)}`);
  }

  const json = await res.json();
  const text: string | undefined =
    json?.candidates?.[0]?.content?.parts?.map((p: { text?: string }) => p.text || "").join("") ||
    json?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("Gemini returned an empty response");
  return text;
}
